name: constructor-env

channels:
  - conda-forge

dependencies:
  - constructor >=3.6.0
  - conda-standalone >=23.11.0
  - menuinst
  - conda >=23.11.0
  - mamba
  - conda-libmamba-solver
  - fmt !=10.2.0
